#!/usr/bin/php
<?php
/**
 * Warm a Magento Full Page Cache.
 * This assumes you have an FPC installed on the target site.
 * If you don't all it will do is create undue load on your server.
 * All the script does is download your sitemap.xml file and hit every url in the list.
 * 
 * In reality this script will work on any site that provides a sitemap.xml file.
 * Please don't use the script to attack websites! Frankly, it won't even work well as
 * a DOS attack, because it executes each request synchronously.
 *
 * Copyright Nathan Nobbe 2015.
 */

// Load the backend class
require __DIR__ . '/MageCacheWarmer.php';

define('MINARGC', 2);
define('MAXARGC', 5);

if($argc < MINARGC) {
    usage();
}

$sFunc  = 'warm';
$iDelay = 0;
$iUnsecure = 0;
$priorityThreshold = 1;

$arguments = $argv;
array_shift($arguments);
while ( count($arguments) ) {
    $param = array_shift($arguments);
    switch ( $param ) {
        case '-h':
            usage();
            break;

        case '-t':
            $sFunc = 'test';
            break;

        case '-k':
            $iUnsecure = 1;
            break;

        default:
            if ( $param[0] != '-' ) {
                $sUrl = $param;
            } else if ( preg_match('/^\-d=([0-9]*)$/', $param, $M) ) {
                $iDelay = intval($M[1]);
            } else if ( preg_match('/^\-p=([\.0-9]*)$/', $param, $M) ) {
                $priorityThreshold = floatval($M[1]);
            } else {
                usage();
            }
    }

}

if ( ! $sUrl ) usage();

try {
    $oMageCacheWarmer = new MageCacheWarmer($sUrl, 'echoCallback', $iDelay, $iUnsecure, $priorityThreshold);
    $fSpeedup         = $oMageCacheWarmer->loadSitemap()->$sFunc();

    if($sFunc == 'test') {
        reportResults($oMageCacheWarmer->getAvgDownloadTime(), true);
    } else {
        reportResults($oMageCacheWarmer->getAvgDownloadTime());
        echo 'Speedup is ' . $fSpeedup . '%' . PHP_EOL; 
    }
} catch(Exception $e) {
    echo "Cache warmer crashed with error: " . PHP_EOL;
    echo $e->getMessage();
    exit(1);
}

/**
 * echo messages from the underlying class.
 */
function echoCallback($sMsg)
{
    echo $sMsg;
}

/**
 * Report the results
 */
function reportResults($fAvgTime, $bTest=false)
{
    $sFinishType = $bTest ? 'testing' : 'warming';

    echo "Finished $sFinishType your Magento site performance" . PHP_EOL;
    echo 'Average page time (in milliseconds): ' . $fAvgTime . PHP_EOL;
}

/**
 * Print the script usage and exit.
 */
function usage()
{
    echo '-------------------------------------' . PHP_EOL;
    echo 'wfpc - Magento full page cache warmer' . PHP_EOL;
    echo '-------------------------------------' . PHP_EOL . PHP_EOL;
    echo 'wfpc [-k] [-h|-t] [-p=min_priority] [-d=delay] <sitemap url>' . PHP_EOL . PHP_EOL;
    echo 'Run help to see the usage options                       : wfpc -h' . PHP_EOL;
    echo 'Run wfpc in test mode to get an idea of page performance: wfpc -t <sitemap url>' . PHP_EOL;
    echo 'Warm the Magento cache                                  : wfpc [-d=delay] <sitemap url>' . PHP_EOL ;
    echo 'Force to continue on unsecure https urls                : wfpc -k <sitemap url>'.PHP_EOL. PHP_EOL;
    echo 'The last form of the command allows a -d option to place a pause of X number of seconds between request' . PHP_EOL;
    exit();
}
